config/routes.rb
Expomobile::Application.routes.draw do
  
  resources :mail_templates

  get "events/change_logo_edit"
  put "events/change_logo_update"
  resources :events

  resources :massive_loads

  get "system_configurations/select_event"
  resources :system_configurations

  get "rating/show_conferences_rating"
  get "rating/show_workshops_rating"
  get "rating/show_application_rating"

  resources :diaries
  
  get "face_to_faces/generate_diary"
  get "face_to_faces/get_interviewee"
  resources :face_to_faces

  resources :activities

  resources :conferences

  get "qr_generator/generate_qr"
 
  resources :sponsors

  post "workshops/set_tolerance"
  get "visits/visits_to_workshops_index"
  get "visits/visits_to_exhibitors_index"
  get "visits/visits_to_workshops_by_subgroup"
  get "visits/visits_to_workshops_by_workshop"
  get "visits/visits_to_exhibitors_by_subgroup"
  get "visits/visits_to_exhibitors_by_exhibitor"
  get "visits/visits_to_workshops"
  get "visits/visits_to_exhibitors"
  get "visits/visits_to_workshops_generate_report"
  get "visits/visits_to_exhibitors_generate_report"
  get "visits/visits_to_workshops_generate_report_by_workshop"
  get "visits/visits_to_exhibitors_generate_report_by_exhibitor"
  get "visits/control_numbers_report_html"
  get "visits/control_numbers_report_pdf"

  resources :expositions
  
  get "mobile_services/get_event_map"
  get "mobile_services/get_event_logo"
  get "mobile_services/get_enabled_options"
  get "mobile_services/rate_conference"
  get "mobile_services/rate_workshop"
  get "mobile_services/rate"
  get "mobile_services/index_diary_days"
  get "mobile_services/show_diary"
  get "mobile_services/index_diaries"
  get "mobile_services/index_face_to_face_days"
  get "mobile_services/show_face_to_face"
  get "mobile_services/index_face_to_faces"
  get "mobile_services/index_activity_days"
  get "mobile_services/show_activity"
  get "mobile_services/index_activities"
  get "mobile_services/index_conference_days"
  get "mobile_services/show_conference"
  get "mobile_services/index_conferences"
  get "mobile_services/show_sponsor"
  get "mobile_services/index_sponsors"
  get "mobile_services/get_attendee_id"
  get "mobile_services/get_attendee_nip"
  get "mobile_services/index_offerts"
  get "mobile_services/show_offert"
  get "mobile_services/index_exhibitors"
  get "mobile_services/show_exhibitor"  
  get "mobile_services/index_workshop_days"
  get "mobile_services/index_exposition_days"
  get "mobile_services/index_workshops"
  get "mobile_services/index_expositions"
  get "mobile_services/index_expositions_names"
  get "mobile_services/register_visit_to_workshop"
  get "mobile_services/register_visit_to_exposition"
  
  resources :hours

  resources :subgroups
  
  get "schedules/subgroup_change"
  post "schedules/deallocate"
  post "schedules/do_association"
  get "schedules/associate_workshop_group"

  resources :rooms

  resources :workshops

  resources :groups

  resources :offerts

  get "exhibitors/get_all_exhibitor_contacts"
  resources :exhibitors
  
  get "attendees/is_active"
  get "attendees/general_attendances_report"
  post "attendees/attend"
  get "attendees/select_email_type"
  post "attendees/send_mails"
  get "attendees/confirm"
  get "attendees/get_subgroups"
  match "foro-ti-chihuahua" => "attendees#register"
  match "register" => "attendees#register"
  match "register_attendee" => "attendees#register_attendee"
  get "attendees/print_gafete_c"
  get "attendees/print_gafete_b"
  get "attendees/print_gafete_a"
  get "attendees/generate_gafete"
  get "attendees/generate_qr"
  get "attendees/get_all_attendee_names"
  get "attendees/get_attendee_by_name"
  get "attendees/get_attendee"
  resources :attendees

  get "welcome/index"
  
  devise_for :users
  
  resources :users

  devise_scope :user do
    get "devise/sessions/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    get "devise/sessions/links" => "devise/sessions#links", :as => :links
    match 'devise/registrations/:id/edit' => 'devise/registrations#edit', :as => :edit_registration
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :map, :logo_bellow, :banner, :exposition_tolerance, :has_activity, :has_conference, :has_facetoface, :has_offert, :has_workshop, :language, :logo, :name, :r_city, :r_country, :r_email, :r_enterprise, :r_job, :r_name, :r_phone, :r_social_reason, :r_state, :r_work_colony, :r_work_street, :r_work_street_number, :r_work_zip, :time_zone, :workshop_tolerance, :start_date, :end_date, :is_free, :place, :e_work_street, :e_work_street_number, :e_work_colony, :e_work_zip, :e_city, :e_state, :e_country, :users_attributes, :token_for_id, :facebook, :twitter
  has_many :groups, :dependent => :destroy
  has_many :subgroups
  has_many :attendees
  has_many :massive_loads, :dependent => :destroy
  has_many :workshops
  has_many :rooms, :dependent => :destroy
  has_many :hours, :dependent => :destroy
  has_many :expositions, :dependent => :destroy
  has_many :exhibitors, :dependent => :destroy
  has_many :offerts
  has_many :face_to_faces
  has_many :sponsors, :dependent => :destroy
  has_many :diaries, :dependent => :destroy
  has_many :conferences, :dependent => :destroy
  has_many :activities, :dependent => :destroy
  has_many :users, :dependent => :destroy
  has_many :attendee_expositions
  has_many :attendee_workshops
  has_many :nips
  has_many :mail_templates, :dependent => :destroy
  has_many :rate_workshops, :dependent => :destroy
  has_many :rate_conferences, :dependent => :destroy
  before_save :token_for_id_to_upcase

  has_attached_file :map,
    :styles => {:medium => "x300",
    :thumb => "x100",
    :mobile => "x60"},
    :default_url => "/assets/default.jpg"
  has_attached_file :logo_bellow,
    :styles => {:medium => "x300",
    :thumb => "x64"},
    :default_url => "/assets/expomobile.png"
  has_attached_file :logo,
    :styles => {:medium => "x300",
    :thumb => "x100",
    :mobile => "x60"},
    :default_url => "/assets/default.jpg"
  has_attached_file :banner,
    :styles => {:medium => "x300",
    :thumb => "x100"},
    :default_url => "/assets/default.jpg"
  validates :logo_bellow, :banner, :logo, :name, :r_email, :r_enterprise, :r_name, :r_social_reason, :start_date, :end_date, :place, :token_for_id, :presence => true
  validates_numericality_of :r_work_zip, :if => :r_work_zip
  validates_format_of :token_for_id, :with => /\A[a-zA-Z]{2}\z/, :if => :token_for_id
  validates :token_for_id, :uniqueness => true
  
  accepts_nested_attributes_for :users
  
  def to_param
    [id, name.parameterize].join("-")
  end
  
  private
  
  def token_for_id_to_upcase
    self.token_for_id.upcase! if !token_for_id.nil?
  end
end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_event, :except => [:show_application_rating]
  
  def show_application_rating
    @ratings = Rating.all
    @total = Rating.count
    @poor_number = Rating.where(:value => 1).count
    @poor_percent = @poor_number * 100.0 / @total
    @fair_number = Rating.where(:value => 2).count
    @fair_percent = @fair_number *  100.0 / @total
    @good_number = Rating.where(:value => 3).count
    @good_percent = @good_number *  100.0 / @total
  end
  
  def show_workshops_rating
    if @event.has_workshop
      @ratings = RateWorkshop.where(:event_id => session[:current_event_id])
    else
      redirect_to root_path
    end
  end
  
  def show_conferences_rating
    if @event.has_conference
      @ratings = RateConference.where(:event_id => session[:current_event_id])
    else
      redirect_to root_path
    end
  end
  
  def load_event
    @event = Event.find_by_id(session[:current_event_id])
  end
end

app/views/rating/show_application_rating.html.erb
<div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t(:bad_total)}:" %></span><span style="width: 150px; font-size: 16px; margin-left: 150px;"><%= " #{@poor_number}/#{@total}" %></span></div>
<div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 150px; font-size: 16px;"><%= (@poor_percent.nan?)? " 0%": " #{"%.2f" % @poor_percent}%" %></span></div><br/>
<div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px;font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t(:fair_total)}:" %></span><span style="width: 150px; font-size: 16px; margin-left: 150px;"><%= " #{@fair_number}/#{@total}" %></span></div>
<div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 150px; font-size: 16px;"><%= (@fair_percent.nan?)? " 0%": " #{"%.2f" % @fair_percent}%" %></span></div><br/>
<div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px;font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t(:good_total)}:" %></span><span style="width: 150px; font-size: 16px; margin-left: 150px;"><%= " #{@good_number}/#{@total}" %></span></div>
<div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 150px; font-size: 16px;"><%= (@good_percent.nan?)? " 0%": " #{"%.2f" % @good_percent}%" %></span></div><br/>

<div id="comments">
  <% if Rating.any? %>
    <h4><%= t(:comments) %></h4>
    <br/><br/>
    <% Rating.all.each do |r| %>
      <p>-- <%= r.comment %></p>
      <hr/>
    <% end %>
  <% else %>
    <p><h3><%= t(:no_comments_available) %></h3></p>
<% end %>
</div>

app/views/rating/show_conferences_rating.html.erb
<h2><%= t(:conferences) %></h2><br/><br/>
<% if @ratings.blank? %>
  <h3><%= t("ratings.there_are_no_ratings") %></h3>
<% else %>
  <% conference_ids = @ratings.pluck(:conference_id).uniq %>
  <% conference_ids.each do |c_id| %>
    <% @rating = @ratings.where(:conference_id => c_id) %>
    <%  @total = @rating.count%>
    <%  @bad_number = @rating.where(:value => 1).count %>
    <%  @bad_percent = @bad_number * 100.0 / @total %>
    <%  @can_improve_number = @rating.where(:value => 2).count %>
    <%  @can_improve_percent = @can_improve_number *  100.0 / @total %>
    <%  @good_number = @rating.where(:value => 3).count %>
    <%  @good_percent = @good_number *  100.0 / @total %>
    <%  @excelent_number = @rating.where(:value => 4).count %>
    <%  @excelent_percent = @excelent_number *  100.0 / @total %>
    <%  @stars_number = ((@bad_number + @can_improve_number * 2 + @good_number * 3 + @excelent_number * 4) / @total).round %>
    <% @conference = Conference.find_by_id(c_id) %>
    <div style="width: 450px; line-height: 36px;">
      <h3 style="width: 250px; display: inline-block;"><%= @conference.name %></h3>
      <div class="stars" style="display: inline-block; float: right;">
        <% @stars_number.times do |t| %>
          <%= image_tag "/assets/star.png", :style => "margin: 0 5px;" %>
        <% end %>
        <% (4 - @stars_number).times do |t| %>
          <%= image_tag "/assets/star_grayscale.png", :style => "margin: 0 5px;" %>
        <% end %>
      </div>
    </div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 200px; font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t("ratings.bad_total")}:" %></span><span style="width: 100px; font-size: 16px; margin-left: 200px; display: inline-block;"><%= " #{@bad_number}/#{@total}" %></span></div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 200px; font-size: 16px;"><%= (@bad_percent.nan?)? " 0%": " #{"%.2f" % @bad_percent}%" %></span></div><br/>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 200px;font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t("ratings.can_improve_total")}:" %></span><span style="width: 100px; font-size: 16px; margin-left: 200px; display: inline-block;"><%= " #{@can_improve_number}/#{@total}" %></span></div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 200px; font-size: 16px;"><%= (@can_improve_percent.nan?)? " 0%": " #{"%.2f" % @can_improve_percent}%" %></span></div><br/>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 200px;font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t("ratings.good_total")}:" %></span><span style="width: 100px; font-size: 16px; margin-left: 200px; display: inline-block;"><%= " #{@good_number}/#{@total}" %></span></div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 200px; font-size: 16px;"><%= (@good_percent.nan?)? " 0%": " #{"%.2f" % @good_percent}%" %></span></div><br/>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 200px;font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t("ratings.excelent_total")}:" %></span><span style="width: 100px; font-size: 16px; margin-left: 200px; display: inline-block;"><%= " #{@excelent_number}/#{@total}" %></span></div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 200px; font-size: 16px;"><%= (@good_percent.nan?)? " 0%": " #{"%.2f" % @excelent_percent}%" %></span></div><br/><br/><br/>
  <% end %>
<% end %>

app/views/rating/show_workshops_rating.html.erb
<h2><%= t(:workshops) %></h2><br/><br/>
<% if @ratings.blank? %>
  <h3><%= t("ratings.there_are_no_ratings") %></h3>
<% else %>
  <% workshop_ids = @ratings.pluck(:workshop_id).uniq %>
  <% workshop_ids.each do |w_id| %>
    <% @rating = @ratings.where(:workshop_id => w_id) %>
    <%  @total = @rating.count%>
    <%  @bad_number = @rating.where(:value => 1).count %>
    <%  @bad_percent = @bad_number * 100.0 / @total %>
    <%  @can_improve_number = @rating.where(:value => 2).count %>
    <%  @can_improve_percent = @can_improve_number *  100.0 / @total %>
    <%  @good_number = @rating.where(:value => 3).count %>
    <%  @good_percent = @good_number *  100.0 / @total %>
    <%  @excelent_number = @rating.where(:value => 4).count %>
    <%  @excelent_percent = @excelent_number *  100.0 / @total %>
    <%  @stars_number = ((@bad_number + @can_improve_number * 2 + @good_number * 3 + @excelent_number * 4) / @total).round %>
    <% @workshop = Workshop.find_by_id(w_id) %>
    <div style="width: 450px; line-height: 36px;">
      <h3 style="width: 250px; display: inline-block;"><%= @workshop.name %></h3>
      <div class="stars" style="display: inline-block; float: right;">
        <% @stars_number.times do |t| %>
          <%= image_tag "/assets/star.png", :style => "margin: 0 5px;" %>
        <% end %>
        <% (4 - @stars_number).times do |t| %>
          <%= image_tag "/assets/star_grayscale.png", :style => "margin: 0 5px;" %>
        <% end %>
      </div>
    </div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 200px; font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t("ratings.bad_total")}:" %></span><span style="width: 100px; font-size: 16px; margin-left: 200px; display: inline-block;"><%= " #{@bad_number}/#{@total}" %></span></div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 200px; font-size: 16px;"><%= (@bad_percent.nan?)? " 0%": " #{"%.2f" % @bad_percent}%" %></span></div><br/>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 200px;font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t("ratings.can_improve_total")}:" %></span><span style="width: 100px; font-size: 16px; margin-left: 200px; display: inline-block;"><%= " #{@can_improve_number}/#{@total}" %></span></div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 200px; font-size: 16px;"><%= (@can_improve_percent.nan?)? " 0%": " #{"%.2f" % @can_improve_percent}%" %></span></div><br/>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 200px;font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t("ratings.good_total")}:" %></span><span style="width: 100px; font-size: 16px; margin-left: 200px; display: inline-block;"><%= " #{@good_number}/#{@total}" %></span></div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 200px; font-size: 16px;"><%= (@good_percent.nan?)? " 0%": " #{"%.2f" % @good_percent}%" %></span></div><br/>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 200px;font-size: 16px; font-weight: bold; position: absolute;"><%= "#{t("ratings.excelent_total")}:" %></span><span style="width: 100px; font-size: 16px; margin-left: 200px; display: inline-block;"><%= " #{@excelent_number}/#{@total}" %></span></div>
    <div style="width: 300px; display: inline-block; line-height: 30px;"><span style="width: 150px; font-size: 16px; font-weight: bold;"><%= "#{t(:percent)}:" %></span><span style="width: 200px; font-size: 16px;"><%= (@good_percent.nan?)? " 0%": " #{"%.2f" % @excelent_percent}%" %></span></div><br/><br/><br/>
  <% end %>
<% end %>