config/routes.rb
Expomobile::Application.routes.draw do
  
  resources :mail_templates

  get "events/change_logo_edit"
  put "events/change_logo_update"
  resources :events

  resources :massive_loads

  get "system_configurations/select_event"
  resources :system_configurations

  get "rating/show_conferences_rating"
  get "rating/show_workshops_rating"
  get "rating/show_application_rating"

  resources :diaries
  
  get "face_to_faces/generate_diary"
  get "face_to_faces/get_interviewee"
  resources :face_to_faces

  resources :activities

  resources :conferences

  get "qr_generator/generate_qr"
 
  resources :sponsors

  post "workshops/set_tolerance"
  get "visits/visits_to_workshops_index"
  get "visits/visits_to_exhibitors_index"
  get "visits/visits_to_workshops_by_subgroup"
  get "visits/visits_to_workshops_by_workshop"
  get "visits/visits_to_exhibitors_by_subgroup"
  get "visits/visits_to_exhibitors_by_exhibitor"
  get "visits/visits_to_workshops"
  get "visits/visits_to_exhibitors"
  get "visits/visits_to_workshops_generate_report"
  get "visits/visits_to_exhibitors_generate_report"
  get "visits/visits_to_workshops_generate_report_by_workshop"
  get "visits/visits_to_exhibitors_generate_report_by_exhibitor"
  get "visits/control_numbers_report_html"
  get "visits/control_numbers_report_pdf"

  resources :expositions
  
  get "mobile_services/get_event_map"
  get "mobile_services/get_event_logo"
  get "mobile_services/get_enabled_options"
  get "mobile_services/rate_conference"
  get "mobile_services/rate_workshop"
  get "mobile_services/rate"
  get "mobile_services/index_diary_days"
  get "mobile_services/show_diary"
  get "mobile_services/index_diaries"
  get "mobile_services/index_face_to_face_days"
  get "mobile_services/show_face_to_face"
  get "mobile_services/index_face_to_faces"
  get "mobile_services/index_activity_days"
  get "mobile_services/show_activity"
  get "mobile_services/index_activities"
  get "mobile_services/index_conference_days"
  get "mobile_services/show_conference"
  get "mobile_services/index_conferences"
  get "mobile_services/show_sponsor"
  get "mobile_services/index_sponsors"
  get "mobile_services/get_attendee_id"
  get "mobile_services/get_attendee_nip"
  get "mobile_services/index_offerts"
  get "mobile_services/show_offert"
  get "mobile_services/index_exhibitors"
  get "mobile_services/show_exhibitor"  
  get "mobile_services/index_workshop_days"
  get "mobile_services/index_exposition_days"
  get "mobile_services/index_workshops"
  get "mobile_services/index_expositions"
  get "mobile_services/index_expositions_names"
  get "mobile_services/register_visit_to_workshop"
  get "mobile_services/register_visit_to_exposition"
  
  resources :hours

  resources :subgroups
  
  get "schedules/subgroup_change"
  post "schedules/deallocate"
  post "schedules/do_association"
  get "schedules/associate_workshop_group"

  resources :rooms

  resources :workshops

  resources :groups

  resources :offerts

  get "exhibitors/get_all_exhibitor_contacts"
  resources :exhibitors
  
  get "attendees/is_active"
  get "attendees/general_attendances_report"
  post "attendees/attend"
  get "attendees/select_email_type"
  post "attendees/send_mails"
  get "attendees/confirm"
  get "attendees/get_subgroups"
  match "foro-ti-chihuahua" => "attendees#register"
  match "register" => "attendees#register"
  match "register_attendee" => "attendees#register_attendee"
  get "attendees/print_gafete_c"
  get "attendees/print_gafete_b"
  get "attendees/print_gafete_a"
  get "attendees/generate_gafete"
  get "attendees/generate_qr"
  get "attendees/get_all_attendee_names"
  get "attendees/get_attendee_by_name"
  get "attendees/get_attendee"
  resources :attendees

  get "welcome/index"
  
  devise_for :users
  
  resources :users

  devise_scope :user do
    get "devise/sessions/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    get "devise/sessions/links" => "devise/sessions#links", :as => :links
    match 'devise/registrations/:id/edit' => 'devise/registrations#edit', :as => :edit_registration
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_filter :authenticate_user!, :load_event
  before_filter :has_workshop?, :only => [:visits_to_workshops_index, :visits_to_workshops_by_workshop, :visits_to_workshops, :visits_to_workshops_generate_report]

  def visits_to_workshops_by_workshop
    if params[:subgroup_id] =~ /\A\d+\z/
      @subgroup_id = params[:subgroup_id]
    end
  end
  
  def visits_to_workshops
    @attendees = []
    @subgroups = {}
    if params[:workshop_id] =~ /\A\d+\z/ && params[:subgroup_id].blank?
      @attendees = @event.attendees.joins("INNER JOIN attendee_workshops a ON attendees.id = a.attendee_id")
      .where("a.workshop_id = #{params[:workshop_id]}")
    elsif params[:workshop_id] =~ /\A\d+\z/ && params[:subgroup_id] =~ /\A\d+\z/
      @attendees = @event.attendees.joins("INNER JOIN subgroups s ON attendees.subgroup_id = s.id")
      .joins("INNER JOIN attendee_workshops a ON attendees.id = a.attendee_id")
      .where("attendees.subgroup_id = #{params[:subgroup_id]} AND a.workshop_id = #{params[:workshop_id]}")
    end
    @attendees.each do |a|
      a[:register_date] = AttendeeWorkshop.find_by_attendee_id_and_workshop_id(a.id, params[:workshop_id]).created_at
      subgroup_name = a.subgroup.name
      if @subgroups.has_key?(subgroup_name)
        @subgroups[subgroup_name] << a
      else
        @subgroups[subgroup_name] = [a]
      end
    end
  end
  
  def visits_to_workshops_generate_report
    @workshop = Workshop.find_by_id(params[:workshop_id])
    
    if !@workshop.nil?
      @subgroups = @event.subgroups.order(:name).each do |s|
        s.attendees.each do |a|
          a[:assisted] = AttendeeWorkshop.where("attendee_id = ? AND workshop_id = ?", a.id, params[:workshop_id]).any?
        end
      end
      render layout: false
    else
      render nothing: true
    end
  end

  def visits_to_exhibitors_by_exhibitor
    
    if params[:subgroup_id] =~ /\A\d+\z/
      @subgroup_id = params[:subgroup_id]
    end
    
  end

  def visits_to_exhibitors
    @attendees = []
    @subgroups = {}
    
    if params[:exhibitor_id] =~ /\A\d+\z/
      @attendees = @event.attendees.joins("INNER JOIN attendee_expositions a ON attendees.id = a.attendee_id")
      .where("a.exhibitor_id = #{params[:exhibitor_id]}")
    elsif
      @attendees = @event.attendees.joins("INNER JOIN subgroups s ON attendees.subgroup_id = s.id")
      .joins("INNER JOIN attendee_expositions a ON attendees.id = a.attendee_id")
      .where("attendees.subgroup_id = #{params[:subgroup_id]} AND a.exhibitor_id = #{params[:exhibitor_id]}")
    end
    
    @attendees.each do |a|
      a[:register_date] = AttendeeExposition.find_by_attendee_id_and_exhibitor_id(a.id, params[:exhibitor_id]).created_at
      subgroup_name = a.subgroup.name
      
      if @subgroups.has_key?(subgroup_name)
        @subgroups[subgroup_name] << a
      else
        @subgroups[subgroup_name] = [a]
      end
      
    end
    
  end
  
  def visits_to_exhibitors_generate_report
    @exhibitor = Exhibitor.find_by_id(params[:exhibitor_id])
    
    if !@exhibitor.nil?
      @subgroups = @event.subgroups.order(:name).each do |s|
        s.attendees.each do |a|
          a[:assisted] = AttendeeExposition.where("attendee_id = ? AND exhibitor_id = ?", a.id, params[:exhibitor_id]).any?
        end
        s.attendees.sort_by!{ |a| [(a[:assisted])? 0: 1, a.id] }
      end
      render layout: false
    else
      render nothing: true
    end
  end
  
  #  def control_numbers_report_html
  #    
  #  end
  
  def control_numbers_report_pdf
    respond_to do |format|
      format.pdf {
        require 'prawn/table'
        pdf = Prawn::Document.new
        @attendees_total = @event.attendees.count
        @logo_url = "#{Rails.root}/public#{@event.logo.url.gsub(/\?.*\z/, "")}"
        pdf.image @logo_url, :height => 50
        pdf.text @event.name, :style => :bold, :size => 14, :align => :center;
        pdf.move_down 10
        pdf.text I18n.t("visit.control_numbers_report"), :style => :bold, :size => 12, :align => :center;
        pdf.move_down 50
        pdf.text Date.today.strftime("%d/%m/%Y")
        pdf.move_down 20
        table_data_1 = [[I18n.t("visit.attendees_total"), @attendees_total], [I18n.t("visit.exhibitors_total"), @event.exhibitors.count], [I18n.t("visit.sponsors_total"), @event.sponsors.count]]
        table_data_1 << [I18n.t("visit.workshops_total"), @event.workshops.count] if @event.has_workshop
        pdf.table(table_data_1) do
          column(1).font_style = :bold
          self.cell_style = { :size => 7 }
        end
        pdf.move_down 20
        pdf.text I18n.t(:attendances), :style => :bold, :size => 10
        pdf.move_down 10
        table_data_2 = [[I18n.t(:exhibitors), "#{"%.1f" % (@event.attendee_expositions.count * 100 / @attendees_total)}%"]] +
        @event.exhibitors.map do |exhibitor|
          [exhibitor.name, "#{"%.1f" % (exhibitor.attendee_expositions.count * 100 / @attendees_total)}%"]
        end.select do |exhibitor, attendance|
          attendance != "0.0%"
        end
        pdf.table(table_data_2) do
          row(0).font_style = :bold
          column(1).font_style = :bold
          self.cell_style = { :size => 7 }
        end
        pdf.move_down 20
        table_data_3 = [[I18n.t("visit.users_using_the_app"), @event.nips.count]]
        table_data_3.insert 0, [I18n.t(:workshops), "#{"%.1f" % (@event.attendee_workshops.count * 100 / @attendees_total)}%"] if @event.has_workshop
        pdf.table(table_data_3) do
          column(1).font_style = :bold
          self.cell_style = { :size => 7 }
        end
        send_data pdf.render, filename: "control_numbers_report_#{Date.today.to_s.gsub("-", "_")}", type: "application/pdf", disposition: "inline"
      }
    end
  end
  
  def load_event
    @event = Event.find_by_id(session[:current_event_id])
  end
  
  def has_workshop?
    unless @event.has_workshop
      flash[:error] = t(:workshops_disabled)
      redirect_to root_path
    end
  end
    
end

app/views/visits/control_numbers_report_html.html.erb
<div style="text-align: center; margin: 20px 0 40px;">
  <h2><%= label_tag t("visit.control_numbers_report") %></h2>
</div>
<div style="line-height: 30px;">
  <% @attendees_total = @event.attendees.count %>
  <table style="margin-bottom: 20px; width: auto; font-size: 16px;">
    <tr>
      <td>
        <%= t("visit.attendees_total") %>
      </td>
      <td style="font-weight: bold;">
        <%= @attendees_total %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t("visit.exhibitors_total") %>
      </td>
      <td style="font-weight: bold;">
        <%= @event.exhibitors.count %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t("visit.sponsors_total") %>
      </td>
      <td style="font-weight: bold;">
        <%= @event.sponsors.count %>
      </td>
    </tr>
    <% if @event.has_workshop %>
      <tr>
        <td>
          <%= t("visit.workshops_total") %>
        </td>
        <td style="font-weight: bold;">
          <%= @event.workshops.count %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= label_tag t(:attendances), nil, :style => "font-weight: bold; font-size: 18px;" %><br/>
  <table style="margin-bottom: 20px; width: auto; font-size: 16px;">
    <tr>
      <td style="font-weight: bold;">
        <%= t(:exhibitors) %>
      </td>
      <td style="font-weight: bold;">
        <%= "#{"%.1f" % (@event.attendee_expositions.count * 100 / @attendees_total)}%" %>
      </td>
    </tr>
    <% @event.exhibitors.each do |exhibitor| %>
      <% if exhibitor.attendee_expositions.count > 0 %>
        <tr>
          <td>
            <%= exhibitor.name %>
          </td>
          <td style="font-weight: bold;">
            <%= "#{"%.1f" % (exhibitor.attendee_expositions.count * 100 / @attendees_total)}%" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
  
  <table style="margin-bottom: 20px; width: auto; font-size: 16px;">
    <% if @event.has_workshop %>
      <tr>
        <td>
          <%= t(:workshops) %>
        </td>
        <td style="font-weight: bold;">
          <%= "#{"%.1f" % (@event.attendee_workshops.count * 100 / @attendees_total)}%" %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>
        <%= t("visit.users_using_the_app") %>
      </td>
      <td style="font-weight: bold;">
        <%= @event.nips.count %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t("visit.users_attended") %>
      </td>
      <td style="font-weight: bold;">
        <%= "#{@event.attendees.where(:attended => true).count}/#{@attendees_total}, #{@event.attendees.where(:attended => true).count * 100 / @attendees_total}%" %>
      </td>
    </tr>
  </table>
  <%= link_to t("visit.generate_pdf_report"), visits_control_numbers_report_pdf_path(:format => "pdf"), :class => "button" %>
</div>