config/routes.rb
Expomobile::Application.routes.draw do
  
  resources :mail_templates

  get "events/change_logo_edit"
  put "events/change_logo_update"
  resources :events

  resources :massive_loads

  get "system_configurations/select_event"
  resources :system_configurations

  get "rating/show_conferences_rating"
  get "rating/show_workshops_rating"
  get "rating/show_application_rating"

  resources :diaries
  
  get "face_to_faces/generate_diary"
  get "face_to_faces/get_interviewee"
  resources :face_to_faces

  resources :activities

  resources :conferences

  get "qr_generator/generate_qr"
 
  resources :sponsors

  post "workshops/set_tolerance"
  get "visits/visits_to_workshops_index"
  get "visits/visits_to_exhibitors_index"
  get "visits/visits_to_workshops_by_subgroup"
  get "visits/visits_to_workshops_by_workshop"
  get "visits/visits_to_exhibitors_by_subgroup"
  get "visits/visits_to_exhibitors_by_exhibitor"
  get "visits/visits_to_workshops"
  get "visits/visits_to_exhibitors"
  get "visits/visits_to_workshops_generate_report"
  get "visits/visits_to_exhibitors_generate_report"
  get "visits/visits_to_workshops_generate_report_by_workshop"
  get "visits/visits_to_exhibitors_generate_report_by_exhibitor"
  get "visits/control_numbers_report_html"
  get "visits/control_numbers_report_pdf"

  resources :expositions
  
  get "mobile_services/get_event_map"
  get "mobile_services/get_event_logo"
  get "mobile_services/get_enabled_options"
  get "mobile_services/rate_conference"
  get "mobile_services/rate_workshop"
  get "mobile_services/rate"
  get "mobile_services/index_diary_days"
  get "mobile_services/show_diary"
  get "mobile_services/index_diaries"
  get "mobile_services/index_face_to_face_days"
  get "mobile_services/show_face_to_face"
  get "mobile_services/index_face_to_faces"
  get "mobile_services/index_activity_days"
  get "mobile_services/show_activity"
  get "mobile_services/index_activities"
  get "mobile_services/index_conference_days"
  get "mobile_services/show_conference"
  get "mobile_services/index_conferences"
  get "mobile_services/show_sponsor"
  get "mobile_services/index_sponsors"
  get "mobile_services/get_attendee_id"
  get "mobile_services/get_attendee_nip"
  get "mobile_services/index_offerts"
  get "mobile_services/show_offert"
  get "mobile_services/index_exhibitors"
  get "mobile_services/show_exhibitor"  
  get "mobile_services/index_workshop_days"
  get "mobile_services/index_exposition_days"
  get "mobile_services/index_workshops"
  get "mobile_services/index_expositions"
  get "mobile_services/index_expositions_names"
  get "mobile_services/register_visit_to_workshop"
  get "mobile_services/register_visit_to_exposition"
  
  resources :hours

  resources :subgroups
  
  get "schedules/subgroup_change"
  post "schedules/deallocate"
  post "schedules/do_association"
  get "schedules/associate_workshop_group"

  resources :rooms

  resources :workshops

  resources :groups

  resources :offerts

  get "exhibitors/get_all_exhibitor_contacts"
  resources :exhibitors
  
  get "attendees/is_active"
  get "attendees/general_attendances_report"
  post "attendees/attend"
  get "attendees/select_email_type"
  post "attendees/send_mails"
  get "attendees/confirm"
  get "attendees/get_subgroups"
  match "foro-ti-chihuahua" => "attendees#register"
  match "register" => "attendees#register"
  match "register_attendee" => "attendees#register_attendee"
  get "attendees/print_gafete_c"
  get "attendees/print_gafete_b"
  get "attendees/print_gafete_a"
  get "attendees/generate_gafete"
  get "attendees/generate_qr"
  get "attendees/get_all_attendee_names"
  get "attendees/get_attendee_by_name"
  get "attendees/get_attendee"
  resources :attendees

  get "welcome/index"
  
  devise_for :users
  
  resources :users

  devise_scope :user do
    get "devise/sessions/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    get "devise/sessions/links" => "devise/sessions#links", :as => :links
    match 'devise/registrations/:id/edit' => 'devise/registrations#edit', :as => :edit_registration
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/exhibitor.rb
class Exhibitor < ActiveRecord::Base
  attr_accessible :name, :email, :contact, :job, :phone, :social_reason, :twitter, :web_page, :work_street, :work_street_number, :work_colony, :work_zip, :logo, :exposition_key, :stand_location, :stand_size, :event_id
  belongs_to :event
  has_many :attendee_expositions, :dependent => :destroy
  has_attached_file :logo,
    :styles => {:medium => "x300",
    :thumb => "x100",
    :mobile => "x60" },
    :default_url => "/assets/default.jpg"
  has_many :offerts, :dependent => :destroy
  before_save :name_to_upcase
  
  validates :name, :social_reason, :event_id, :presence => true
  #validates :phone, :email, :contact, :job, :presence => true
  validates :contact, :uniqueness => { :scope => :event_id }
  #validates :social_reason, :name, :uniqueness => { :scope => :event_id }
  
  private
  
  def name_to_upcase
    self.name.mb_chars.upcase! if !name.nil?
    self.social_reason.mb_chars.upcase! if !social_reason.nil?
  end
end

app/controllers/exhibitors_controller.rb
class ExhibitorsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    if params[:with_offerts] == "1"
      @exhibitors = Exhibitor.joins("RIGHT OUTER JOIN offerts o ON exhibitors.id = o.exhibitor_id").where(:event_id => session[:current_event_id]).uniq
      @exhibitors.each {|e| e[:mobile_logo_url] = e.logo.url(:mobile)}
    elsif !params[:search].blank?
      @exhibitors = Exhibitor.where("event_id = #{session[:current_event_id]} AND contact LIKE '%#{params[:search]}%'").order('id DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @exhibitors = Exhibitor.where(:event_id => session[:current_event_id]).order('id DESC').paginate(:per_page => 10, :page => params[:page])
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exhibitors }
    end
  end

  # GET /exhibitors/1
  # GET /exhibitors/1.json
  def show
    @exhibitor = Exhibitor.find(params[:id])
    if @exhibitor.event_id != session[:current_event_id].to_i
      flash[:error] = t(:not_correspond)
      redirect_to exhibitors_path and return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exhibitor }
    end
  end

  # GET /exhibitors/new
  # GET /exhibitors/new.json
  def new
    @exhibitor = Exhibitor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exhibitor }
    end
  end

  # GET /exhibitors/1/edit
  def edit
    @exhibitor = Exhibitor.find(params[:id])
    if @exhibitor.event_id != session[:current_event_id].to_i
      flash[:error] = t(:not_correspond)
      redirect_to exhibitors_path and return
    end
  end

  # POST /exhibitors
  # POST /exhibitors.json
  def create
    @exhibitor = Exhibitor.new(params[:exhibitor])
    
    while @exhibitor.exposition_key.nil?
      random_value = Array.new(3) {[*'0'..'9', *'a'..'z'].sample}.join
      @exists = Workshop.find_by_workshop_key(random_value) || Exhibitor.find_by_exposition_key(random_value)
        
      if @exists.nil?
        @exhibitor.exposition_key = random_value
      end
    end

    respond_to do |format|
      if @exhibitor.save
        format.html { redirect_to @exhibitor, notice: t(:successfully_created) }
        format.json { render json: @exhibitor, status: :created, location: @exhibitor }
      else
        format.html { render action: "new" }
        format.json { render json: @exhibitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exhibitors/1
  # PUT /exhibitors/1.json
  def update
    @exhibitor = Exhibitor.find(params[:id])

    respond_to do |format|
      if @exhibitor.update_attributes(params[:exhibitor])
        format.html { redirect_to @exhibitor, notice: t(:successfully_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exhibitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitors/1
  # DELETE /exhibitors/1.json
  def destroy
    @exhibitor = Exhibitor.find(params[:id])
    @exhibitor.destroy

    respond_to do |format|
      format.html { redirect_to exhibitors_url }
      format.json { head :no_content }
    end
  end
  
  def get_all_exhibitor_contacts
    @exhibitors = Exhibitor.where(:event_id => session[:current_event_id]).uniq.pluck(:contact)
    
    render json: @exhibitors
  end
end

app/views/exhibitors/_form.html.erb
<%= render "layouts/first_tab" %>
<%= form_for(@exhibitor, :html => { :multipart => true }) do |f| %>
  <% if @exhibitor.errors.any? %>
    <div id="error_explanation">
      <% if @exhibitor.errors.count == 1 %>
        <h2><%= t('activerecord.errors.template.header.one', :model => t("activerecord.models.exhibitor")) %></h2>
      <% else %>
        <h2><%= t('activerecord.errors.template.header.other', :model => t("activerecord.models.exhibitor"), :count => @exhibitor.errors.count) %></h2>
      <% end %>
      <ul>
        <% @exhibitor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset class="column-left">
    <p class="field">
      <%= f.label t("exhibitor.logo") %>
      <%= f.file_field :logo %>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.name") %>
      <%= f.text_field :name, :class=>"text-input medium-input", :required => true %><span class="required">*</span>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.social_reason") %>
      <%= f.text_field :social_reason, :class=>"text-input medium-input", :required => true %><span class="required">*</span>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.contact") %>
      <%= f.text_field :contact, :class=>"text-input medium-input", :required => true %><span class="required">*</span>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.email") %>
      <%= f.email_field :email, :class=>"text-input medium-input", :required => true %><span class="required">*</span>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.job") %>
      <%= f.text_field :job, :class=>"text-input small-input", :required => true %><span class="required">*</span>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.phone") %>
      <%= f.text_field :phone, :class=>"text-input small-input", :required => true %><span class="required">*</span>
    </p>
  </fieldset>
  <fieldset class="column-right">
    <p class="field">
      <%= f.label t("exhibitor.work_street") %>
      <%= f.text_field :work_street, :class=>"text-input medium-input" %>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.work_street_number") %>
      <%= f.text_field :work_street_number, :class=>"text-input small-input" %>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.work_colony") %>
      <%= f.text_field :work_colony, :class=>"text-input medium-input" %>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.work_zip") %>
      <%= f.text_field :work_zip, :class=>"text-input small-input", :style => "width: 10% !important;", :required => true, :pattern => "[0-9]{5}" %><span class="required">*</span>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.web_page") %>
      <%= f.text_field :web_page, :class=>"text-input medium-input" %>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.twitter") %>
      <%= f.text_field :twitter, :class=>"text-input small-input" %>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.stand_location") %>
      <%= f.text_field :stand_location, :class=>"text-input small-input" %>
    </p>

    <p class="field">
      <%= f.label t("exhibitor.stand_size") %>
      <%= f.text_field :stand_size, :class=>"text-input small-input" %>
    </p>
    <%= f.hidden_field :event_id, :value => session[:current_event_id] %>
  </fieldset>
<div class="clear"></div>
  <p><span class="required">*</span>&nbsp;&nbsp;&nbsp;<%= t(:required) %></p>  

  <div class="form-actions">
    <%= f.submit nil, :class => "button" %>
  </div>

<% end %>

app/views/exhibitors/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "exhibitors" %>
<% end %>

<div style="margin: 25px">
  <%= form_tag exhibitors_path, :method => "get", :id => "search_form" do %>
    <%= label_tag t(:search_by_contact) %>
    <%= text_field_tag :search, params[:search], :id => "search_field", :class => "text-input small-input", :style => "margin-right: 10px;" %>
  <% end %>
</div>
<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
  <table>
    <thead>
      <tr>
<%#*<th><input class="check-all" type="checkbox" /></th>%>
        <th>ID</th>
        <th><%= t'exhibitor.exposition_key' %></th>
        <th><%= (t'atten.gafete').upcase %></th>
        <th><%= t'exhibitor.name' %></th>
        <th><%= t'exhibitor.social_reason' %></th>
        <th><%= t'exhibitor.contact' %></th>
        <th><%= t'exhibitor.email' %></th>
        <th><%= t'exhibitor.job' %></th>
        <th><%= t'exhibitor.phone' %></th>
        <th><%= t'exhibitor.stand_location' %></th>
        <th><%= t'exhibitor.stand_size' %></th>
      </tr>

    </thead>

    <tfoot>
      <tr>
        <td colspan="13">
<%#*<div class="bulk-actions align-left">%>
<%#= render "layouts/select_action" %>
<%#*</div>%>
          <%= render "layouts/pagination" %>
          <div class="clear"></div>
        </td>
      </tr>
    </tfoot>

    <tbody>
      <% @exhibitors.each do |exhibitor| %>
        <tr>
  <%#*<td><input type="checkbox" /></td>%>
  <%#if can? :show, Exhibitor %>
  <%#*<td><%= link_to exhibitor.id, exhibitor, :class => 'button' </td>%>
  <%#else%>
          <td><%= label exhibitor.id, exhibitor.id %></td>
  <%# end %>
          <% @model = exhibitor %>
          <td><%= exhibitor.exposition_key %><br/><%= link_to t(:qr_code), qr_generator_generate_qr_path(:key => exhibitor.exposition_key, :exhibitor => true, :exhibitor_name => exhibitor.name, :exhibitor_job => exhibitor.job, :stand_location => exhibitor.stand_location), :class => "qr_code button" %></td>
          
          <td style="vertical-align: bottom;"><%= link_to t("atten.generate_gafete"), attendees_generate_gafete_path(
              :a_name => exhibitor.contact, :e_tradename => exhibitor.name, :e_phone => exhibitor.phone, :a_cellphone => nil,
              :a_email => exhibitor.email, :e_address => "#{exhibitor.work_street} #{exhibitor.work_street_number}, #{exhibitor.work_colony}", 
              :a_web => exhibitor.web_page, :layout => "true", :is_exhibitor => "true"
              ), :class => "button" %></td>
          
          <td><%= exhibitor.name %></td>
          
          <td><%= exhibitor.social_reason %></td>
          
          <td><%= exhibitor.contact %></td>
          
          <td><%= exhibitor.email %></td>
          
          <td><%= exhibitor.job %></td>
          
          <td><%= exhibitor.phone %></td>
          
          <td><%= exhibitor.stand_location %></td>
          
          <td><%= exhibitor.stand_size %></td>
          <%= render "layouts/index_links" %>
        <% end %>
    </tbody>
  </table>
  <%= render "layouts/action_links" %>
</div> 
<%= render "layouts/second_tab" %>