config/routes.rb
Expomobile::Application.routes.draw do
  
  resources :mail_templates

  get "events/change_logo_edit"
  put "events/change_logo_update"
  resources :events

  resources :massive_loads

  get "system_configurations/select_event"
  resources :system_configurations

  get "rating/show_conferences_rating"
  get "rating/show_workshops_rating"
  get "rating/show_application_rating"

  resources :diaries
  
  get "face_to_faces/generate_diary"
  get "face_to_faces/get_interviewee"
  resources :face_to_faces

  resources :activities

  resources :conferences

  get "qr_generator/generate_qr"
 
  resources :sponsors

  post "workshops/set_tolerance"
  get "visits/visits_to_workshops_index"
  get "visits/visits_to_exhibitors_index"
  get "visits/visits_to_workshops_by_subgroup"
  get "visits/visits_to_workshops_by_workshop"
  get "visits/visits_to_exhibitors_by_subgroup"
  get "visits/visits_to_exhibitors_by_exhibitor"
  get "visits/visits_to_workshops"
  get "visits/visits_to_exhibitors"
  get "visits/visits_to_workshops_generate_report"
  get "visits/visits_to_exhibitors_generate_report"
  get "visits/visits_to_workshops_generate_report_by_workshop"
  get "visits/visits_to_exhibitors_generate_report_by_exhibitor"
  get "visits/control_numbers_report_html"
  get "visits/control_numbers_report_pdf"

  resources :expositions
  
  get "mobile_services/get_event_map"
  get "mobile_services/get_event_logo"
  get "mobile_services/get_enabled_options"
  get "mobile_services/rate_conference"
  get "mobile_services/rate_workshop"
  get "mobile_services/rate"
  get "mobile_services/index_diary_days"
  get "mobile_services/show_diary"
  get "mobile_services/index_diaries"
  get "mobile_services/index_face_to_face_days"
  get "mobile_services/show_face_to_face"
  get "mobile_services/index_face_to_faces"
  get "mobile_services/index_activity_days"
  get "mobile_services/show_activity"
  get "mobile_services/index_activities"
  get "mobile_services/index_conference_days"
  get "mobile_services/show_conference"
  get "mobile_services/index_conferences"
  get "mobile_services/show_sponsor"
  get "mobile_services/index_sponsors"
  get "mobile_services/get_attendee_id"
  get "mobile_services/get_attendee_nip"
  get "mobile_services/index_offerts"
  get "mobile_services/show_offert"
  get "mobile_services/index_exhibitors"
  get "mobile_services/show_exhibitor"  
  get "mobile_services/index_workshop_days"
  get "mobile_services/index_exposition_days"
  get "mobile_services/index_workshops"
  get "mobile_services/index_expositions"
  get "mobile_services/index_expositions_names"
  get "mobile_services/register_visit_to_workshop"
  get "mobile_services/register_visit_to_exposition"
  
  resources :hours

  resources :subgroups
  
  get "schedules/subgroup_change"
  post "schedules/deallocate"
  post "schedules/do_association"
  get "schedules/associate_workshop_group"

  resources :rooms

  resources :workshops

  resources :groups

  resources :offerts

  get "exhibitors/get_all_exhibitor_contacts"
  resources :exhibitors
  
  get "attendees/is_active"
  get "attendees/general_attendances_report"
  post "attendees/attend"
  get "attendees/select_email_type"
  post "attendees/send_mails"
  get "attendees/confirm"
  get "attendees/get_subgroups"
  match "foro-ti-chihuahua" => "attendees#register"
  match "register" => "attendees#register"
  match "register_attendee" => "attendees#register_attendee"
  get "attendees/print_gafete_c"
  get "attendees/print_gafete_b"
  get "attendees/print_gafete_a"
  get "attendees/generate_gafete"
  get "attendees/generate_qr"
  get "attendees/get_all_attendee_names"
  get "attendees/get_attendee_by_name"
  get "attendees/get_attendee"
  resources :attendees

  get "welcome/index"
  
  devise_for :users
  
  resources :users

  devise_scope :user do
    get "devise/sessions/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    get "devise/sessions/links" => "devise/sessions#links", :as => :links
    match 'devise/registrations/:id/edit' => 'devise/registrations#edit', :as => :edit_registration
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/views/layouts/_action_links.erb
<% can_index = %w{system_configurations}.exclude?(controller_name) %>
<br/><br/>
<% if %w{activities offerts expositions conferences diaries massive_loads}.include?(controller_name) %>
  <% new_text = t(:new_record_female, :record => eval("t('activerecord.models.#{controller_name.singularize}')")) %>
<% else %>
  <% new_text = t(:new_record_male, :record => eval("t('activerecord.models.#{controller_name.singularize}')")) %>
<% end %>
<% if controller.action_name == "new" or controller.action_name == "create" %>
  <%= link_to(t(:return_to_index, :model => eval("t(:#{controller_name})").downcase), eval("#{controller_name}_path"), :class=>"button") if can_index %>
<% elsif controller.action_name == "edit" or controller.action_name == "update" %>
  <%= link_to(t(:return_to_index, :model => eval("t(:#{controller_name})").downcase), eval("#{controller_name}_path"), :class=>"button") if can_index %>
  <%= link_to t(:show_record, :record => eval("t('activerecord.models.#{controller_name.singularize}')")), eval("@#{controller_name.singularize}"), :class=>"button" %>
  <% if current_user.role.is_super_admin || current_user.role.is_admin %>
    <% if %w{mail_templates system_configurations}.exclude?(controller_name) %>
      <%= link_to new_text, eval("new_#{controller_name.singularize}_path"), :class=>"button" %>
    <% end %>
  <% end %>
<% elsif controller.action_name == "show" %>
  <%= link_to(t(:return_to_index, :model => eval("t(:#{controller_name})").downcase), eval("#{controller_name}_path"), :class=>"button") if can_index && !session[:current_event_id].nil? %>
  <% if %w{massive_loads}.exclude?(controller_name) %>
    <% if current_user == @user %>
      <% @edit_path = "edit_registration_path(@user)" %>
    <% else %>
      <% @edit_path = "edit_#{controller_name.singularize}_path(@#{controller_name.singularize})" %>
    <% end %>
    <%= link_to t(:edit_record, :record => eval("t('activerecord.models.#{controller_name.singularize}')")), eval(@edit_path), :class=>"button" %>
  <% end %>
  <% if current_user.role.is_super_admin || current_user.role.is_admin %>
    <% if %w{mail_templates system_configurations}.exclude?(controller_name) && !session[:current_event_id].nil? %>
      <%= link_to new_text, eval("new_#{controller_name.singularize}_path"), :class=>"button" %>
    <% end %>
  <% end %>
<% elsif controller.action_name == "index" && (current_user.role.is_super_admin || current_user.role.is_admin) %>
  <% if %w{mail_templates}.exclude?(controller_name) %>
    <%= link_to new_text, eval("new_#{controller_name.singularize}_path"), :class=>"button" %>
  <% end %>
<% end %>

app/views/layouts/_index_links.erb
<td><%=link_to @model, :class=>"nav-header" do%>
    <img src="/assets/icons/information.png" alt="Edit" />
  <%end%></td>
<% if !%w{massive_loads}.include?(controller_name) %>
  <% if current_user == @model %>
    <% @edit_path = "edit_registration_path(@model)" %>
  <% else %>
    <% @edit_path = "edit_#{controller_name.singularize}_path(@model)" %>
  <% end %>
  <td><%=link_to eval(@edit_path), :class=>"nav-header" do%>
      <img src="/assets/icons/pencil.png" alt="Edit" />
    <%end%></td>
<% end %>
<% if !%w{mail_templates system_configurations}.include?(controller_name) %>
  <td><%=link_to @model, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"nav-header" do%>
      <img src="/assets/icons/cross.png" alt="Delete" />
    <%end%>
  </td>
<% end %>

app/views/layouts/_sidebar.erb
<div id="sidebar"><div id="sidebar-wrapper"> <!-- Sidebar with logo and menu -->

    <h1 id="sidebar-title"><a href="#">Expomobile</a></h1>

    <!-- Logo (221px wide) -->
    <%= link_to image_tag("/assets/expomobile.png", :id => "logo", :alt => ""), "/", :style => "display: block;" %>
    <!-- Sidebar Profile links -->
    <div id="profile-links">
      <% if @event.nil? %>
        <div id="current_time"><%= Time.now %></div>
      <% else %>
        <div><%= link_to @event.name, @event %></div>
        <div id="current_time">
          <% if current_user.role.is_super_admin? %>
            <div id="current_time"><%= Time.now %></div>
          <% else %>
            <div id="current_time"><%= Time.now.in_time_zone(@event.time_zone) %></div>
          <% end %>
        </div>
      <% end %>
      <div><%= link_to current_user.fullname, current_user %>, <%= t(:signed_in) %></div>
      <br />
      <%= link_to t(:home), root_path %> | 
      <%= link_to t(:logout), destroy_user_session_path %>
    </div>
    <ul id="main-nav">  <!-- Accordion Menu -->
      <li>     
        <%= link_to t(:home).mb_chars.upcase, root_path, :class=> "nav-top-item no-submenu" + (controller_name == "welcome" ? " current": ""), :id => "1main" %>
      </li>
      <% if current_user.role.is_super_admin %>
        <li>     
          <%= link_to t(:configuration).mb_chars.upcase, edit_system_configuration_path(SystemConfiguration.first), :class=> "nav-top-item no-submenu" + (controller_name == "system_configurations" ? " current": ""), :id => "2main" %>
        </li>
        <li>
          <a href="#" class="nav-top-item mainlinks<%= " current" if %{events}.include?(controller_name) %>" id="3main"> <!-- Add the class "current" to current menu item -->
            <%= t(:events).mb_chars.upcase %>
          </a>
          <ul>
            <% @models = %w{Event} %>
            <% @models.each do |model| %>
              <li><%= link_to eval("t(:#{model.pluralize.downcase})"), eval("#{model.downcase.pluralize}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "index" ? "current": "" %></li>
              <li><%= link_to t(:new_record_male, :record => eval("t('activerecord.models.#{model.downcase}')")), eval("new_#{model.downcase}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "new" ? "current": "" %></li>
            <% end %>
          </ul>
        </li>
      <% elsif current_user.role.is_admin %>
        <li>     
          <%= link_to t(:configuration).mb_chars.upcase, edit_event_path(session[:current_event_id]), :class=> "nav-top-item no-submenu" + (controller_name == "events" ? " current": ""), :id => "2main" %>
        </li>
      <% end %>
      <% unless session[:current_event_id].nil? %>
        <li>
          <% @is_exhibitor = @is_exhibitor.nil? ? false: @is_exhibitor %>
          <a href="#" class="nav-top-item mainlinks<%= " current" if %{attendees groups subgroups mail_templates massive_loads}.include?(controller_name) && !@is_exhibitor && !(controller_name == "attendees" && controller.action_name == "general_attendances_report") %>" id="4main"> <!-- Add the class "current" to current menu item -->
            <%= t(:attendees).mb_chars.upcase %>
          </a>
          <ul>
            <% @models = %w{Attendee Group Subgroup Massive_Load Mail_Template} %>
            <% @models.each do |model| %>
              <li><%= link_to eval("t(:#{model.pluralize.downcase})"), eval("#{model.downcase.pluralize}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "index" ? "current": "" %></li>
              <% if %w{Massive_Load}.include?(model) %>
                <% new_text = t(:new_record_female, :record => eval("t('activerecord.models.#{model.downcase}')")) %>
              <% else %>
                <% new_text = t(:new_record_male, :record => eval("t('activerecord.models.#{model.downcase}')")) %>
              <% end %>
              <% if %w{Mail_Template}.exclude?(model) %>
                <li><%= link_to t(new_text, :record => eval("t('activerecord.models.#{model.downcase}')")), eval("new_#{model.downcase}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "new" ? "current": "" %></li>
              <% end %>
            <% end %>
            <li><%= link_to t(:send_mails), attendees_select_email_type_path %></li>
          </ul>
        </li>
        <% if @event.try(:has_workshop) %>
          <li>
            <a href="#" class="nav-top-item mainlinks<%= " current" if %{workshops rooms hours schedules}.include?(controller_name) %>" id="5main"> <!-- Add the class "current" to current menu item -->
              <%= t(:workshops).mb_chars.upcase %>
            </a>
            <ul>
              <% @models = %w{Workshop Room Hour} %>
              <% @models.each do |model| %>
                <li><%= link_to eval("t(:#{model.pluralize.downcase})"), eval("#{model.downcase.pluralize}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "index" ? "current": "" %></li>
                <li><%= link_to t(:new_record_male, :record => eval("t('activerecord.models.#{model.downcase}')")), eval("new_#{model.downcase}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "new" ? "current": "" %></li>
              <% end %>
              <li><%= link_to t("hour.associate_workshop_group"), schedules_associate_workshop_group_path, :class => controller_name == "schedules" && controller.action_name == "associate_workshop_group" ? "current": "" %></li>
            </ul>
          </li>
        <% end %>
        <li>
          <% @is_exhibitor = @is_exhibitor.nil? ? false: @is_exhibitor %>
          <a href="#" class="nav-top-item mainlinks<%= " current" if %{expositions stands exhibitors offerts}.include?(controller_name) || @is_exhibitor %>" id="6main"> <!-- Add the class "current" to current menu item -->
            <%= t(:expositions).mb_chars.upcase %>
          </a>
          <ul>
            <% @models = %w{Exposition Exhibitor Offert} %>
            <% @models.each do |model| %>
              <% if %w{Exposition Exhibitor}.include?(model) || eval("@event.try(:has_#{model.downcase})") %>
                <li><%= link_to eval("t(:#{model.pluralize.downcase})"), eval("#{model.downcase.pluralize}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "index" ? "current": "" %></li>
                <% if %w{Exposition Offert}.include?(model) %>
                  <% new_text = t(:new_record_female, :record => eval("t('activerecord.models.#{model.downcase}')")) %>
                <% else %>
                  <% new_text = t(:new_record_male, :record => eval("t('activerecord.models.#{model.downcase}')")) %>
                <% end %>
                <li><%= link_to new_text, eval("new_#{model.downcase}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "new" ? "current": "" %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <li>
          <a href="#" class="nav-top-item mainlinks<%= " current" if %{face_to_faces sponsors}.include?(controller_name) %>" id="7main"> <!-- Add the class "current" to current menu item -->
            <%= (@event.try(:has_facetoface))? t(:face_to_faces).mb_chars.upcase: t(:sponsors).mb_chars.upcase %>
          </a>
          <ul>
            <% @models = %w{Face_To_Face Sponsor} %>
            <% @models.each do |model| %>
              <% if %w{Sponsor}.include?(model) || eval("@event.try(:has_#{model.camelize.downcase})") %>
                <li><%= link_to eval("t(:#{model.pluralize.downcase})"), eval("#{model.downcase.pluralize}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "index" ? "current": "" %></li>
                <li><%= link_to t(:new_record_male, :record => eval("t('activerecord.models.#{model.downcase}')")), eval("new_#{model.downcase}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "new" ? "current": "" %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <li>
          <a href="#" class="nav-top-item mainlinks<%= " current" if %{diaries conferences activities}.include?(controller_name) %>" id="8main"> <!-- Add the class "current" to current menu item -->
            <%= (t"activerecord.models.diary").mb_chars.upcase %>
          </a>
          <ul>
            <% @models = %w{Diary Conference Activity} %>
            <% @models.each do |model| %>
              <% if %w{Diary}.include?(model) || eval("@event.try(:has_#{model.downcase})") %>
                <li><%= link_to eval("t(:#{model.pluralize.downcase})"), eval("#{model.downcase.pluralize}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "index" ? "current": "" %></li>
                <% if %w{Conference Activity}.include?(model) %>
                  <% new_text = t(:new_record_female, :record => eval("t('activerecord.models.#{model.downcase}')")) %>
                <% else %>
                  <% new_text = t(:new_record_male, :record => eval("t('activerecord.models.#{model.downcase}')")) %>
                <% end %>
                <li><%= link_to new_text, eval("new_#{model.downcase}_path"), :class => controller_name == model.pluralize.downcase && controller.action_name == "new" ? "current": "" %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <li>
          <a href="#" class="nav-top-item mainlinks<%= " current" if controller_name == "visits" || (controller_name == "attendees" && controller.action_name == "general_attendances_report") %>" id="9main"> <!-- Add the class "current" to current menu item -->
            <%= t(:attendances).mb_chars.upcase %>
          </a>
          <ul>
            <% if @event.try(:has_workshop) %>
              <li><%= link_to t("visit.attendances_to_workshops"), visits_visits_to_workshops_index_path, :class => controller_name == "visits" && (controller.action_name == "visits_to_workshops_index" || controller.action_name == "visits_to_workshops" || controller.action_name == "visits_to_workshops_by_subgroup" || controller.action_name == "visits_to_workshops_by_workshop") ? "current": "" %></li>
            <% end %>
            <li><%= link_to t("visit.attendances_to_exhibitors"), visits_visits_to_exhibitors_index_path, :class => controller_name == "visits" && (controller.action_name == "visits_to_exhibitors_index" || controller.action_name == "visits_to_exhibitors" || controller.action_name == "visits_to_exhibitors_by_subgroup" || controller.action_name == "visits_to_exhibitors_by_exhibitor") ? "current": "" %></li>
            <li><%= link_to t("visit.control_numbers_report"), visits_control_numbers_report_html_path, :class => controller_name == "visits" && (controller.action_name == "control_numbers_report_html") ? "current": "" %></li>
            <li><%= link_to t("general_attendances_report"), attendees_general_attendances_report_path, :class => controller_name == "attendees" && (controller.action_name == "general_attendances_report") ? "current": "" %></li>
          </ul>
        </li>
        <% if current_user.role.is_super_admin %>
          <li>
            <a href="#" class="nav-top-item mainlinks<%= " current" if controller_name == "users" %>" id="10main"> <!-- Add the class "current" to current menu item -->
              <%= t(:users).mb_chars.upcase %>
            </a>
            <ul>
              <li><%= link_to t(:users), users_path, :class => controller_name == "users" && controller.action_name == "index" ? "current": "" %></li>
              <li><%= link_to t(:new_record_male, :record => t("activerecord.models.user")), new_user_path, :class => controller_name == "users" && controller.action_name == "new" ? "current": "" %></li>
            </ul>
          </li>
          <li>
          <a href="#" class="nav-top-item mainlinks<%= " current" if controller_name == "rating" %>" id="11main"> <!-- Add the class "current" to current menu item -->
            <%= t(:rating).mb_chars.upcase %>
          </a>
          <ul>
            <li><%= link_to t("ratings.application_rating"), rating_show_application_rating_path, :class => controller_name == "rating" && (controller.action_name == "show_application_rating") ? "current": "" %></li>
            <% if @event.try(:has_workshop) %>
              <li><%= link_to t("ratings.workshops_rating"), rating_show_workshops_rating_path, :class => controller_name == "rating" && (controller.action_name == "show_workshops_rating") ? "current": "" %></li>
            <% end %>
            <% if @event.try(:has_conference) %>
              <li><%= link_to t("ratings.conferences_rating"), rating_show_conferences_rating_path, :class => controller_name == "rating" && (controller.action_name == "show_conferences_rating") ? "current": "" %></li>
            <% end %>
          </ul>
          </li>
        <% end %>
      <% end %>
    </ul> <!-- End #main-nav -->

  </div></div> <!-- End #sidebar -->

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

  <head>

    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

    <title>
      <% @event = Event.find_by_id(session[:current_event_id]) unless session[:current_event_id].nil? %>
      <% if @event.nil? %>
        <%= "EXPOMOBILE: " + eval("t(:" + controller_name + ")") %>
      <% else %>
        <%= "#{@event.name}: " + eval("t(:" + controller_name + ")") %>
      <% end %>
    </title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "jquery.dataTables" %>
    <%= csrf_meta_tags %>

    <!-- Internet Explorer Fixes Stylesheet -->

    <!--[if lte IE 7]>
            <link rel="stylesheet" href="resources/css/ie.css" type="text/css" media="screen" />
    <![endif]-->

    <!-- Internet Explorer .png-fix -->

    <!--[if IE 6]>
            <script type="text/javascript" src="assets/scripts/DD_belatedPNG_0.0.7a.js"></script>
            <script type="text/javascript">
                    DD_belatedPNG.fix('.png_bg, img, li');
            </script>
    <![endif]-->

  </head>

  <body>
    <div id="body-wrapper"> <!-- Wrapper for the radial gradient background -->
      <%= render "layouts/sidebar" %>
      <div id="main-content"> <!-- Main Content Section with everything -->

        <noscript> <!-- Show a notification if the user has disabled javascript -->
          <div class="notification error png_bg">
            <div>
              Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
            </div>
          </div>
        </noscript>
        <!-- Page Head -->
        <% if controller_name == "welcome" %>
          <h2><%= "#{t(:welcome)} #{current_user.fullname}" %><%= " #{t(:to_event)} #{@event.name}" unless @event.nil? %></h2>     
        <% end %>
        <div id="images-container">
          <% unless @event.nil? %>
            <div class="logo-div"><%= image_tag @event.logo.url, :class => "logo-img", :height => 94, :style => "height: 94px; -ms-interpolation-mode: bicubic;" %></div>
            <div class="banner-div"><%= image_tag @event.banner.url, :class => "logo-img", :height => 110, :style => "height: 110px; -ms-interpolation-mode: bicubic;" %></div>
            <div id="settings-div">
              <%= link_to image_tag("/assets/settings.png"), events_change_logo_edit_path(:id => @event.id) %>
            </div>
          <% end %>
        </div>

        <div id="catalogs">
          <% unless @event.nil? %>
            <p id="page-intro"><%= t(:catalogs) %></p>
            <style>
              /*.shortcut-buttons-set { list-style: none; padding: 0; margin: 0; }*/
            </style>
            <ul class="shortcut-buttons-set"> <!-- Replace the icons URL's with your own -->

              <% unless @event.nil? %>

                <% if @event.has_workshop %>
                  <li><%= link_to workshops_path, :class => "shortcut-button" do %>
                      <span><%= image_tag("/assets/#{t(:workshops).downcase}.png") %></span>
                    <% end %></li>
                <% end %>

                <% if @event.has_conference %>
                  <li><%= link_to conferences_path, :class => "shortcut-button" do %>
                      <span><%= image_tag("/assets/#{t(:conferences).downcase}.png") %></span>
                    <% end %></li>
                <% end %>

                <li><%= link_to expositions_path, :class => "shortcut-button" do %>
                    <span><%= image_tag("/assets/#{t("activerecord.models.exposition").tr("ó", "o")}.png") %></span>
                  <% end %></li>

                <% if @event.has_offert %>
                  <li><%= link_to offerts_path, :class => "shortcut-button" do %>
                      <span><%= image_tag("/assets/#{t(:offerts).downcase}.png") %></span>
                    <% end %></li>
                <% end %>

                <% if @event.has_facetoface %>
                  <li><%= link_to face_to_faces_path, :class => "shortcut-button" do %>
                      <span><%= image_tag("/assets/#{t(:face_to_faces).gsub(" ", "").downcase}.png") %></span>
                    <% end %></li>
                <% end %>

                <li><%= link_to sponsors_path, :class => "shortcut-button" do %>
                    <span><%= image_tag("/assets/#{t(:sponsors).downcase}.png") %></span>
                  <% end %></li>
              <% end %>

              <li><%= link_to diaries_path, :class => "shortcut-button" do %>
                  <span><%= image_tag("/assets/#{t("activerecord.models.diary").downcase}.png") %></span>
                <% end %></li>

              <% if @event.has_activity %>
                <li><%= link_to activities_path, :class => "shortcut-button" do %>
                    <span><%= image_tag("/assets/#{t(:activities).downcase}.png") %></span>
                  <% end %></li>
              <% end %>

            </ul><!-- End .shortcut-buttons-set -->
          <% end %>
        </div>

        <div class="clear"></div> <!-- End .clear -->

        <div class="content-box"><!-- Start Content Box -->

          <div class="content-box-header">
            <h3><%= eval("t(:#{controller_name})") if %w{welcome}.exclude?(controller_name) %></h3>
            <% if controller_name == "schedules" && action_name == "associate_workshop_group" %>
              <% if Hour.where(:event_id => session[:current_event_id]).any? %>
                <ul class="content-box-tabs">
                  <% i = 1 %>
                  <% Hour.where(:event_id => session[:current_event_id]).order(:start_date).pluck(:start_date).map{ |s| s.strftime("%d/%m/%Y") }.uniq.each do |d| %>
                    <% if flash[:schedule_start_date].nil? %>
                      <% default_tab = 1 %>
                    <% else %>
                      <% default_tab = i if flash[:schedule_start_date].strftime("%d/%m/%Y") == d %>
                    <% end %>
                    <li><a href="#tab<%= i %>" class="<%= "default-tab" if i == default_tab %>"><%= d %></a></li>
                    <% i += 1 %>
                  <% end %>
                </ul>
              <% end %>
            <% end %>
            <div class="clear"></div>

          </div> <!-- End .content-box-header -->
          <div class="content-box-content">  
            <% if flash[:notice] %>
              <div class="notification attention png_bg">
                <a href="#" class="close"><img src="/assets/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
                <div>
                  <%= flash[:notice] %>
                </div>
              </div>
            <% end %>
            <% if flash[:alert] %>
              <div class="notification information png_bg">
                <a href="#" class="close"><img src="/assets/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
                <div>
                  <%= flash[:alert] %>
                </div>
              </div>
            <% end %>
            <% if flash[:success] %>
              <div class="notification success png_bg">
                <a href="#" class="close"><img src="/assets/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
                <div>
                  <%= flash[:success] %>
                </div>
              </div>
            <% end %>
            <% if flash[:error] %>
              <div class="notification error png_bg">
                <a href="#" class="close"><img src="/assets/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
                <div>
                  <%= flash[:error] %>
                </div>
              </div>
            <% end %>
            <%= yield %>
          </div> <!-- End .content-box-content -->

        </div> <!-- End .content-box -->

        <div class="clear"></div>

        <div id="footer">
        </div><!-- End #footer -->

      </div> <!-- End #main-content -->

    </div>
    <script type="text/javascript">
      $(function() {
        $(".field_with_errors").children("select, textarea, input:not(.other)").css({border: "3px solid #ffb7b7"});
        $(".field_with_errors").children("input[type='checkbox'], input[type='radio']").css({outline: "3px solid #ffb7b7"});
        $(".field_with_errors").each(function() {
          $(this).after($(this).html());
        });
        $(".field_with_errors").remove();
      });
    </script>
    <%= yield :javascript_includes %>
    <%= javascript_include_tag "highcharts" %>
    <%= javascript_include_tag "exporting" %>
  </body>

</html>